dask/zict

zict/file.py
zict/tests/test_file.py

Also speed up keys(), `__iter__`, `__len__` and `__contains__` by avoiding filesystem access.

Fix #12: File.keys() and File.__iter__ buggy with escaped keys

---

zict/lru.py
zict/tests/test_lru.py

This will be useful when managing dask worker memory

Add LRU.evict method

---

setup.py

`split()` already returns a list, by wrapping the expresion `open(...)....split('\n')` with `[]`, you make it a list of list of str, where a list of str is required.

 Fix install_requires

---

.gitignore
doc/source/conf.py
doc/source/index.rst

- Add missing classes and sort all classes in alphabetical order.
- Configure autosummary extension (which was already used, but in docstrings
that were previously unpublished).
- Create a _static directory to silence a sphinx warning.
It's possible that these classes were intentionally omitted from the documentation because they are considered less stable. If so, feel free to disregard this PR.

DOC: Add classes missing from API documentation.

---

zict/tests/test_zip.py
zict/tests/utils_test.py

Import ABC from collections.abc instead of collections for Python 3.9 compatibility

---

.travis.yml
setup.py
zict/common.py
zict/file.py
zict/func.py
zict/lmdb.py
zict/lru.py
zict/sieve.py
zict/tests/test_buffer.py
zict/tests/test_file.py
zict/tests/test_func.py
zict/tests/test_lmdb.py
zict/tests/test_lru.py
zict/tests/test_sieve.py
zict/tests/utils_test.py
zict/zip.py

Python 2 has reached EOL and many other projects in the ecosystem (e.g. Dask, NumPy, Pandas) have dropped support for Python 3.5 (see [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html))

Drop Python 2 / 3.5 and add Python 3.7 / 3.8 support

---

zict/buffer.py
zict/tests/test_buffer.py

Two changes here to the Buffer
* Only call the weight function once during setitem
* In case a key, currently stored in fast, is overwritten by a large value, delete the fast entry

Dup keys fast slow

---

zict/file.py

- Fixing - https://github.com/rapidsai/dask-cuda/issues/232
- issue is observed during multiple dask cuda worker creation
and some of the dask-cuda worker died after failing with EEXIST
error.

Fix dask cuda worker's race condition failure

---

.travis.yml
pytest.ini
setup.cfg
zict/__init__.py
zict/buffer.py
zict/common.py
zict/file.py
zict/func.py
zict/lmdb.py
zict/lru.py
zict/sieve.py
zict/tests/test_buffer.py
zict/tests/test_file.py
zict/tests/test_func.py
zict/tests/test_lmdb.py
zict/tests/test_lru.py
zict/tests/test_sieve.py
zict/tests/test_zip.py
zict/tests/utils_test.py
zict/zip.py

This PR adds `flake8` and `black` checks for linting and code style

Add code linting and style check

---

zict/tests/test_file.py
zict/tests/test_lmdb.py
zict/tests/test_zip.py

This removes the following class of warnings when running tests
```python
zict/tests/test_file.py:11
/home/runner/work/zict/zict/zict/tests/test_file.py:11: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
Use @pytest.fixture instead; they are the same.
def fn():
```

Avoid deprecated `pytest.yield_fixture` usage

---

setup.py
zict/__init__.py
zict/buffer.py
zict/lru.py
zict/tests/test_buffer.py
zict/tests/test_lru.py

Based on https://github.com/dask/zict/pull/47
Closes https://github.com/dask/distributed/issues/5364
This PR adds LRU to catch exceptions raised during a callback. 
This is ready for review.
cc: @jrbourbeau @crusaderky

LRU raises

---

.github/workflows/pre-commit.yml
.github/workflows/test.yml
.gitignore
.pre-commit-config.yaml
CONTRIBUTING.md
doc/source/changelog.rst
doc/source/conf.py
setup.cfg
setup.py
zict/lmdb.py
zict/tests/utils_test.py

- Drop Python 3.6
- Formally add support for Python 3.9 and 3.10
- Migrate code linters to pre-commit
- Fix failures vs. latest version of black (closes #54)
- Pin versions of black and flake8

Drop Python 3.6; add 3.9 and 3.10; use pre-commit

---

README.rst

In https://github.com/dask/zict/pull/55 we updated the name of the GHA that runs our tests. This is a small follow up PR to update the status badge on our README accordingly (currently it's red, but should be green)
cc @crusaderky when you get a moment

Update `README` badges

---

zict/file.py
zict/tests/test_file.py

Adds a flag to `File` to allow data to be read in with `mmap`. This can be useful in a few ways.
1. Other processes loading the same data can reuse the same memory
2. Reading data from disk can be deferred until needed
3. The OS (instead of the application) manages mapping data from disk to memory (so it can more easily free it as well)

Allow file `mmap`ing

---

setup.py

- This prevents pip from incorrectly installing 2.1.0 in Python 2
- I detected this problem in https://github.com/spyder-ide/spyder-kernels/pull/374 because that package still supports Python 2.

Add `python_requires` to `setup.py`

---

.gitignore
.pre-commit-config.yaml
MANIFEST.in
README.rst
doc/source/changelog.rst
doc/source/conf.py
setup.cfg
setup.py
zict/__init__.py
zict/buffer.py
zict/common.py
zict/file.py
zict/func.py
zict/lmdb.py
zict/lru.py
zict/sieve.py
zict/tests/test_zip.py
zict/tests/utils_test.py
zict/zip.py

- Annotate everything
- Enforce mypy validation in CI
- Let mypy running on other packages read type annotations from zict
- Move contents of setup.py to setup.cfg
- Blocked by https://github.com/dask/distributed/pull/5905
- Follow-up: #61 
- Follow-up: https://github.com/python/mypy/issues/708

Type annotations

---

doc/source/changelog.rst
zict/common.py
zict/tests/test_func.py

Descope pickled outputs sooner

---

doc/source/changelog.rst
doc/source/index.rst
setup.cfg
zict/__init__.py
zict/buffer.py
zict/cache.py
zict/common.py
zict/func.py
zict/lru.py
zict/sieve.py
zict/tests/test_cache.py

- Closes https://github.com/dask/distributed/issues/3756
- Blocks https://github.com/dask/distributed/pull/5936

New class zict.Cache

---

zict/file.py

Provide a brief blurb about the `File` constructor's `memmap` flag.
xref: https://github.com/dask/zict/pull/70#pullrequestreview-1130135194
cc @jrbourbeau

[DOC] `File(..., memmap=False)`

---

.github/workflows/test.yml
doc/requirements.txt
doc/source/changelog.rst
requirements.txt
setup.cfg
zict/buffer.py
zict/func.py
zict/lru.py
zict/sieve.py
zict/tests/test_lru.py

- Remove dependency from heapdict
- Speed up LRU
- Fix broken LRU state if the underlying mapping is non-empty at init
```python
In [1] from zict import LRU
In [2]: d = LRU(100, {})
In [3]: %time for i in range(1000): d[i] = i
```
Before: 2.29 ms
After: 995 us

Remove heapdict dependency; speed up LRU; non-empty LRU init

---

.github/workflows/test.yml
doc/source/changelog.rst
zict/file.py
zict/lmdb.py
zict/tests/test_file.py
zict/tests/test_lmdb.py

- Run CI on Windows and MacOSX
- Add support for pathlib and pytest tmpdir to File and LMDB
- Enable LMDB memory mapped I/O on MacOSX
- Fix broken LMDB on Windows (the full file is allocated in advance, regardless of memory mapping)

MacOSX and Windows CI

---

.pre-commit-config.yaml
doc/source/conf.py
doc/source/index.rst
setup.cfg
zict/__init__.py
zict/buffer.py
zict/common.py
zict/func.py
zict/lru.py
zict/sieve.py
zict/tests/test_buffer.py
zict/tests/test_cache.py
zict/tests/test_file.py
zict/tests/test_func.py
zict/tests/test_lmdb.py
zict/zip.py

- In the rendered documentation as well as in the `objects.inv` file for intersphinx, hide implementation modules; e.g. change from `zict.buffer.Buffer` to `zict.Buffer`.
- Tighten mypy validation, bringing it in line with dask/distributed

Sphinx and mypy tweaks

---

doc/source/changelog.rst
doc/source/index.rst
zict/buffer.py
zict/cache.py
zict/file.py
zict/func.py
zict/lmdb.py
zict/lru.py
zict/sieve.py
zict/tests/test_lru.py
zict/zip.py

- Partially closes https://github.com/dask/distributed/issues/4424
Make the library partially thread-safe.
Crucially, this makes `distributed.Worker.data.fast.__getitem__()` thread-safe, which means that `Worker.execute` and `get_data` will only need to offload to a thread if any of the keys are actually spilled.
Actual thread-offloadling mechanics will be in later PRs (both here and in distributed).

Partial thread-safety

---

.github/workflows/test.yml
.pre-commit-config.yaml
doc/source/changelog.rst
setup.cfg
zict/cache.py
zict/common.py
zict/tests/test_common.py
zict/zip.py

- Drop support for Python 3.7
- Automatically call close() on dereferencing
- Add unit tests for update() and close()

Drop support for Python 3.7

---

doc/source/changelog.rst
doc/source/index.rst
zict/__init__.py
zict/buffer.py
zict/cache.py
zict/common.py
zict/lru.py
zict/tests/test_buffer.py
zict/tests/test_lru.py
zict/tests/test_utils.py
zict/utils.py

- Partially closes dask/distributed#4424

Delayed eviction from LRU

---

doc/source/changelog.rst
zict/file.py
zict/tests/test_file.py

- Partially closes dask/distributed#4424
- Blocked by https://github.com/dask/distributed/pull/7691
`zict.File` is now almost fully thread-safe, with the only caveat that you can't call `__setitem__` on the same key at the same time from two different threads. Crucially for dask/distributed#4424, you can now delete a key from the main thread while the same key is being either read or written from an offloaded thread.

Enhanced thread-safety in zict.File

---

.github/workflows/test.yml
continuous_integration/environment.yml
setup.cfg

- Use conda environment file
- Add support for `@pytest.mark.repeat`
- Add support for `@pytest.mark.timeout` and set default timeout on all tests
- ~~Add support for `@pytest.mark.xfail` (currently unused)~~
- ~~Add support for `@pytest.mark.flaky` (currently unused)~~

Misc CI tweaks

---

zict/tests/test_file.py
zict/tests/test_lmdb.py

https://docs.pytest.org/en/7.2.x/how-to/tmp_path.html#tmpdir-and-tmpdir-factory

Replace obsolete tmpdir fixture with tmp_path

---

.coveragerc
doc/source/changelog.rst
zict/buffer.py
zict/cache.py
zict/file.py
zict/func.py
zict/lmdb.py
zict/sieve.py
zict/tests/test_buffer.py
zict/tests/test_cache.py
zict/tests/test_lru.py
zict/tests/test_zip.py
zict/tests/utils_test.py
zict/zip.py

- Closes #61 
- Partially closes https://github.com/dask/distributed/issues/4424
- Fix RuntimeError when a thread is iterating on Buffer, e.g. `distributed.worker_state_machine.WorkerStateMachine.validate_state()`, while another is evicting/restoring a key

Thread-safe Buffer.__items__; proper KeysView, ItemsView, ValuesView

---

doc/source/changelog.rst
zict/lmdb.py
zict/tests/conftest.py
zict/tests/test_file.py
zict/tests/test_lmdb.py
zict/tests/test_zip.py
zict/tests/utils_test.py
zict/zip.py

- Robustly check key/value types in File, LMDB, Zip
- Thoroughly check for file descriptor leaks
- ``Zip.__contains__`` no longer reads the value from disk
- ``Zip.__setitem__`` will now raise when updating an already-existing key instead of quietly corrupting the mapping

Enhancements to File, LMDB, Zip

---

doc/source/changelog.rst
doc/source/index.rst
setup.cfg
zict/__init__.py
zict/buffer.py
zict/cache.py
zict/common.py
zict/file.py
zict/func.py
zict/lmdb.py
zict/lru.py
zict/sieve.py
zict/tests/conftest.py
zict/tests/test_buffer.py
zict/tests/test_cache.py
zict/tests/test_common.py
zict/tests/test_file.py
zict/tests/test_lru.py
zict/tests/test_sieve.py
zict/tests/test_utils.py
zict/tests/utils_test.py
zict/utils.py
zict/zip.py

- Partially closes https://github.com/dask/distributed/pull/7686
- The whole lockless thread safety design from #82 and #90 was extremely brittle. This PR swaps it for an industry-standard RLock based design.
- Full thread safety for all classes (except Zip and LMDB), with much less caveats than before
- Follow-up: #99

Lock-based thread safety

---

continuous_integration/environment.yml
doc/source/changelog.rst
doc/source/index.rst
zict/__init__.py
zict/async_buffer.py
zict/lru.py
zict/tests/conftest.py
zict/tests/test_async_buffer.py
zict/tests/test_lru.py

- Partially closes https://github.com/dask/distributed/pull/7686

AsyncBuffer

---

zict/tests/utils_test.py

Prevent test timeout on a single CPU
